name: example
description: Flutter Enhancer example

version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_enhancer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

publish_to: none